### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by sachinchavan9** [ksharindam/quartz-browser-qt5#1]
```
Microsoft Windows [Version 10.0.16299.431]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\mjdev> pip install quartz-browser
Collecting quartz-browser
  Downloading https://files.pythonhosted.org/packages/c0/b9/ae9102d955beecf6f213796237b17c8774125d26ccacef1a5b2842770cca/quartz-browser-2.1.0.tar.gz (86kB)
    100% |################################| 92kB 364kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\mjdev\appdata\local\temp\pip-install-j1nfio\quartz-browser\setup.py", line 2, in <module>
        from quartz_browser import __version__
      File "quartz_browser\__init__.py", line 56, in <module>
        homedir = os.environ['HOME']
      File "c:\python27\lib\os.py", line 425, in __getitem__
        return self.data[key.upper()]
    KeyError: 'HOME'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\mjdev\appdata\local\temp\pip-install-j1nfio\quartz-browser\

C:\Users\mjdev>

```

**Comment by ksharindam** [comment]
Actually this software is only supported in Linux platform. And I have no plan to support windows and other platforms.

**Comment by sachinchavan9** [comment]
I will try this on Linux later @ksharindam

**Comment by ksharindam** [comment]
Now, I have added windows support.

**Comment by sachinchavan9** [comment]
Thanks @ksharindam
