### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QtWebKit'

### ISSUE THREAD

**Issue by openedhardware** [ksharindam/quartz-browser-qt5#11]
OS: Raspbian Buster Desktop
Python version: 3.7.3
PyQt5 installation: `sudo apt install python3-pyqt5`

I got this error:
```
pi@raspberrypi:~ $ quartz bing.com --kiosk
Traceback (most recent call last):
  File "/usr/local/bin/quartz", line 5, in <module>
    from quartz_browser.main import main
  File "/usr/local/lib/python3.7/dist-packages/quartz_browser/main.py", line 23, in <module>
    from PyQt5.QtWebKit import QWebSettings
ModuleNotFoundError: No module named 'PyQt5.QtWebKit'
```

**Comment by ksharindam** [comment]
Qtwebkit not installed.
Run
sudo apt install python3-pyqt5.qtwebkit

**Comment by openedhardware** [comment]
It works. Thanks!
