### ISSUE TITLE
This code is not working on Raspbian-stretch OS, any help?

### ISSUE THREAD

**Issue by VIkash2601** [ksharindam/quartz-browser-qt5#5]
I tried to run **./quartz** but unable to execute it.

The error I'm getting is as:

```
Traceback (most recent call last):
  File "./quartz", line 6, in <module>
    from quartz_browser.main import main
  File "/home/pi/Desktop/Project Files/quartz-browser-qt5-master/quartz_browser/main.py", line 23, in <module>
    from PyQt5.QtWebKit import QWebSettings
ImportError: No module named 'PyQt5.QtWebKit'
```

**Comment by ksharindam** [comment]
Have you installed python3-pyqt5.qtwebkit package?

**Comment by smartm0use** [comment]
I got the same problem and I solved installing the missing package:

`sudo apt-get install python3-pyqt5.qtwebkit`
